### ISSUE TITLE
Why so broken on arch??

### ISSUE THREAD

**Issue by javalsai** [ErrorNoInternet/asmfetch#2]
![image](https://github.com/user-attachments/assets/a67f60d8-e2a0-488b-bc00-4944f37d0f35)

- [x] No uptime space separation (8911e4581e32d817f1377b1f46bb1a5792c8b3a1)
- [X] Bad logo https://github.com/ErrorNoInternet/asmfetch/blob/2b1936bf07d396bab27a0bfab8b0b200087d75fe/asmfetch.S#L28
- [x] Bad desktop detection (+ Hyprland logo on xmonad)

**Comment by javalsai** [comment]
Actually, artix*, basically the same tho

**Comment by ErrorNoInternet** [comment]
Logos/symbols are hardcoded and can only be changed at assemble time, desktop requires XDG_CURRENT_DESKTOP, uptime string is the only bug here

**Comment by javalsai** [comment]
> desktop requires XDG_CURRENT_DESKTOP

Then put `<unknown>` or at least don't print that empty space?

**Comment by ErrorNoInternet** [comment]
> > desktop requires XDG_CURRENT_DESKTOP
> 
> Then put `<unknown>` or at least don't print that empty space?

muh performance

**Comment by javalsai** [comment]
And ig a generic logo instead of fedora if the current one can't be determined is the thing to do too.

**Comment by javalsai** [comment]
> > > desktop requires XDG_CURRENT_DESKTOP
> > 
> > 
> > Then put `<unknown>` or at least don't print that empty space?
> 
> muh performance

:nerd_face:

**Comment by ErrorNoInternet** [comment]
> And ig a generic logo instead of fedora if the current one can't be determined is the thing to do too.

There is no OS determining, that would slow down things by a lot

**Comment by javalsai** [comment]
> > And ig a generic logo instead of fedora if the current one can't be determined is the thing to do too.
> 
> There is no OS determining, that would slow down things by a lot

Then how u do it, compile time?

**Comment by ErrorNoInternet** [comment]
Bottom of the README:

> # Customization
> It wasn't designed to be very customizable or dynamic; tons of things are hardcoded, but you can tweak one or two things (including the logo) by modifying the includes in asmfetch.S and symbols in symbols.S.

**Comment by ErrorNoInternet** [comment]
Found a reasonable compromise for a missing XDG_CURRENT_DESKTOP in ebb3c0da036fac03716684ba30fb24a62bc2d44e

**Comment by javalsai** [comment]
> Found a reasonable compromise for a missing XDG_CURRENT_DESKTOP in [ebb3c0d](https://github.com/ErrorNoInternet/asmfetch/commit/ebb3c0da036fac03716684ba30fb24a62bc2d44e)

![image](https://github.com/user-attachments/assets/0abaabe7-c5be-400e-b123-5fd22a55f7da)
fair enough (doing arch logo as yk)
