### ISSUE TITLE
does not detect bash

### ISSUE THREAD

**Issue by anselmjiayu** [ErrorNoInternet/asmfetch#6]
my `$SHELL` is set as `/bin/bash`. asmfetch shows shell as `SETS_TITLE=0`. `asmfetch | xxd` attached
[xxd.txt](https://github.com/user-attachments/files/16679897/xxd.txt)

**Comment by ErrorNoInternet** [comment]
has this been fixed with 64f81e285088393ad6b0bdca7c8cde377f3efcc3?

**Comment by anselmjiayu** [comment]
fixed now, thanks
